<?xml version="1.0" encoding="utf-8"?><Database Name="HotelManagerNew1" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-REHBC99\SQLEXPRESS;Initial Catalog=HotelManagerNew1;Integrated Security=True" SettingsObjectName="PMQLKS.Properties.Settings" SettingsPropertyName="HotelManagerNew1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.chucvu" Member="chucvus">
    <Type Name="chucvu">
      <Column Name="macv" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tencv" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="chucvu_nhanvien" Member="nhanviens" ThisKey="macv" OtherKey="macv" Type="nhanvien" />
    </Type>
  </Table>
  <Table Name="dbo.datphong" Member="datphongs">
    <Type Name="datphong">
      <Column Name="madp" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="manv" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="makh" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="tenlp" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ngaydat" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngayden" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngaydi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="soluong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dsphong" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="trangthaitt" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="datphong_hoadon" Member="hoadons" ThisKey="madp" OtherKey="madp" Type="hoadon" />
      <Association Name="khachhang_datphong" Member="khachhang" ThisKey="makh" OtherKey="makh" Type="khachhang" IsForeignKey="true" />
      <Association Name="loaiphong_datphong" Member="loaiphong" ThisKey="tenlp" OtherKey="tenlp" Type="loaiphong" IsForeignKey="true" />
      <Association Name="nhanvien_datphong" Member="nhanvien" ThisKey="manv" OtherKey="manv" Type="nhanvien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dichvu" Member="dichvus">
    <Type Name="dichvu">
      <Column Name="madv" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tendv" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="gia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="dichvu_hoadon" Member="hoadons" ThisKey="madv" OtherKey="madv" Type="hoadon" />
    </Type>
  </Table>
  <Table Name="dbo.hoadon" Member="hoadons">
    <Type Name="hoadon">
      <Column Name="mahd" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="madp" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="madv" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ngaylap" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tongtien" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="datphong_hoadon" Member="datphong" ThisKey="madp" OtherKey="madp" Type="datphong" IsForeignKey="true" />
      <Association Name="dichvu_hoadon" Member="dichvu" ThisKey="madv" OtherKey="madv" Type="dichvu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.khachhang" Member="khachhangs">
    <Type Name="khachhang">
      <Column Name="makh" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="cmnd" Type="System.String" DbType="Char(9) NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="khachhang_datphong" Member="datphongs" ThisKey="makh" OtherKey="makh" Type="datphong" />
    </Type>
  </Table>
  <Table Name="dbo.loaiphong" Member="loaiphongs">
    <Type Name="loaiphong">
      <Column Name="tenlp" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="soluongtrong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="giaphong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="soluongco" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="loaiphong_datphong" Member="datphongs" ThisKey="tenlp" OtherKey="tenlp" Type="datphong" />
      <Association Name="loaiphong_phong" Member="phongs" ThisKey="tenlp" OtherKey="tenlp" Type="phong" />
    </Type>
  </Table>
  <Table Name="dbo.nhanvien" Member="nhanviens">
    <Type Name="nhanvien">
      <Column Name="manv" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="macv" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ngaysinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="gioitinh" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="cmnd" Type="System.String" DbType="Char(9) NOT NULL" CanBeNull="false" />
      <Column Name="diachi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="nhanvien_datphong" Member="datphongs" ThisKey="manv" OtherKey="manv" Type="datphong" />
      <Association Name="chucvu_nhanvien" Member="chucvu" ThisKey="macv" OtherKey="macv" Type="chucvu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.phong" Member="phongs">
    <Type Name="phong">
      <Column Name="maphong" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenlp" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="tinhtrang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="loaiphong_phong" Member="loaiphong" ThisKey="tenlp" OtherKey="tenlp" Type="loaiphong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="tentaikhoan" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="matkhau" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="quyen" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>