#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMQLKS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HotelManagerNew1")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertchucvu(chucvu instance);
    partial void Updatechucvu(chucvu instance);
    partial void Deletechucvu(chucvu instance);
    partial void Insertdatphong(datphong instance);
    partial void Updatedatphong(datphong instance);
    partial void Deletedatphong(datphong instance);
    partial void Insertdichvu(dichvu instance);
    partial void Updatedichvu(dichvu instance);
    partial void Deletedichvu(dichvu instance);
    partial void Inserthoadon(hoadon instance);
    partial void Updatehoadon(hoadon instance);
    partial void Deletehoadon(hoadon instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertloaiphong(loaiphong instance);
    partial void Updateloaiphong(loaiphong instance);
    partial void Deleteloaiphong(loaiphong instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    partial void Insertphong(phong instance);
    partial void Updatephong(phong instance);
    partial void Deletephong(phong instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    #endregion
		
		public dbDataContext() : 
				base(global::PMQLKS.Properties.Settings.Default.HotelManagerNew1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chucvu> chucvus
		{
			get
			{
				return this.GetTable<chucvu>();
			}
		}
		
		public System.Data.Linq.Table<datphong> datphongs
		{
			get
			{
				return this.GetTable<datphong>();
			}
		}
		
		public System.Data.Linq.Table<dichvu> dichvus
		{
			get
			{
				return this.GetTable<dichvu>();
			}
		}
		
		public System.Data.Linq.Table<hoadon> hoadons
		{
			get
			{
				return this.GetTable<hoadon>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<loaiphong> loaiphongs
		{
			get
			{
				return this.GetTable<loaiphong>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<phong> phongs
		{
			get
			{
				return this.GetTable<phong>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chucvu")]
	public partial class chucvu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _macv;
		
		private string _tencv;
		
		private EntitySet<nhanvien> _nhanviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmacvChanging(string value);
    partial void OnmacvChanged();
    partial void OntencvChanging(string value);
    partial void OntencvChanged();
    #endregion
		
		public chucvu()
		{
			this._nhanviens = new EntitySet<nhanvien>(new Action<nhanvien>(this.attach_nhanviens), new Action<nhanvien>(this.detach_nhanviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macv", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string macv
		{
			get
			{
				return this._macv;
			}
			set
			{
				if ((this._macv != value))
				{
					this.OnmacvChanging(value);
					this.SendPropertyChanging();
					this._macv = value;
					this.SendPropertyChanged("macv");
					this.OnmacvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tencv", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string tencv
		{
			get
			{
				return this._tencv;
			}
			set
			{
				if ((this._tencv != value))
				{
					this.OntencvChanging(value);
					this.SendPropertyChanging();
					this._tencv = value;
					this.SendPropertyChanged("tencv");
					this.OntencvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chucvu_nhanvien", Storage="_nhanviens", ThisKey="macv", OtherKey="macv")]
		public EntitySet<nhanvien> nhanviens
		{
			get
			{
				return this._nhanviens;
			}
			set
			{
				this._nhanviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.chucvu = this;
		}
		
		private void detach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.chucvu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.datphong")]
	public partial class datphong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madp;
		
		private string _manv;
		
		private string _makh;
		
		private string _tenlp;
		
		private System.DateTime _ngaydat;
		
		private System.DateTime _ngayden;
		
		private System.DateTime _ngaydi;
		
		private int _soluong;
		
		private string _dsphong;
		
		private string _trangthaitt;
		
		private EntitySet<hoadon> _hoadons;
		
		private EntityRef<khachhang> _khachhang;
		
		private EntityRef<loaiphong> _loaiphong;
		
		private EntityRef<nhanvien> _nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadpChanging(string value);
    partial void OnmadpChanged();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnmakhChanging(string value);
    partial void OnmakhChanged();
    partial void OntenlpChanging(string value);
    partial void OntenlpChanged();
    partial void OnngaydatChanging(System.DateTime value);
    partial void OnngaydatChanged();
    partial void OnngaydenChanging(System.DateTime value);
    partial void OnngaydenChanged();
    partial void OnngaydiChanging(System.DateTime value);
    partial void OnngaydiChanged();
    partial void OnsoluongChanging(int value);
    partial void OnsoluongChanged();
    partial void OndsphongChanging(string value);
    partial void OndsphongChanged();
    partial void OntrangthaittChanging(string value);
    partial void OntrangthaittChanged();
    #endregion
		
		public datphong()
		{
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			this._khachhang = default(EntityRef<khachhang>);
			this._loaiphong = default(EntityRef<loaiphong>);
			this._nhanvien = default(EntityRef<nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madp", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madp
		{
			get
			{
				return this._madp;
			}
			set
			{
				if ((this._madp != value))
				{
					this.OnmadpChanging(value);
					this.SendPropertyChanging();
					this._madp = value;
					this.SendPropertyChanged("madp");
					this.OnmadpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenlp", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string tenlp
		{
			get
			{
				return this._tenlp;
			}
			set
			{
				if ((this._tenlp != value))
				{
					if (this._loaiphong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntenlpChanging(value);
					this.SendPropertyChanging();
					this._tenlp = value;
					this.SendPropertyChanged("tenlp");
					this.OntenlpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydat", DbType="Date NOT NULL")]
		public System.DateTime ngaydat
		{
			get
			{
				return this._ngaydat;
			}
			set
			{
				if ((this._ngaydat != value))
				{
					this.OnngaydatChanging(value);
					this.SendPropertyChanging();
					this._ngaydat = value;
					this.SendPropertyChanged("ngaydat");
					this.OnngaydatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayden", DbType="Date NOT NULL")]
		public System.DateTime ngayden
		{
			get
			{
				return this._ngayden;
			}
			set
			{
				if ((this._ngayden != value))
				{
					this.OnngaydenChanging(value);
					this.SendPropertyChanging();
					this._ngayden = value;
					this.SendPropertyChanged("ngayden");
					this.OnngaydenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydi", DbType="Date NOT NULL")]
		public System.DateTime ngaydi
		{
			get
			{
				return this._ngaydi;
			}
			set
			{
				if ((this._ngaydi != value))
				{
					this.OnngaydiChanging(value);
					this.SendPropertyChanging();
					this._ngaydi = value;
					this.SendPropertyChanged("ngaydi");
					this.OnngaydiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int NOT NULL")]
		public int soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dsphong", DbType="NVarChar(200)")]
		public string dsphong
		{
			get
			{
				return this._dsphong;
			}
			set
			{
				if ((this._dsphong != value))
				{
					this.OndsphongChanging(value);
					this.SendPropertyChanging();
					this._dsphong = value;
					this.SendPropertyChanged("dsphong");
					this.OndsphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthaitt", DbType="NVarChar(30)")]
		public string trangthaitt
		{
			get
			{
				return this._trangthaitt;
			}
			set
			{
				if ((this._trangthaitt != value))
				{
					this.OntrangthaittChanging(value);
					this.SendPropertyChanging();
					this._trangthaitt = value;
					this.SendPropertyChanged("trangthaitt");
					this.OntrangthaittChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="datphong_hoadon", Storage="_hoadons", ThisKey="madp", OtherKey="madp")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_datphong", Storage="_khachhang", ThisKey="makh", OtherKey="makh", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.datphongs.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.datphongs.Add(this);
						this._makh = value.makh;
					}
					else
					{
						this._makh = default(string);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_datphong", Storage="_loaiphong", ThisKey="tenlp", OtherKey="tenlp", IsForeignKey=true)]
		public loaiphong loaiphong
		{
			get
			{
				return this._loaiphong.Entity;
			}
			set
			{
				loaiphong previousValue = this._loaiphong.Entity;
				if (((previousValue != value) 
							|| (this._loaiphong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaiphong.Entity = null;
						previousValue.datphongs.Remove(this);
					}
					this._loaiphong.Entity = value;
					if ((value != null))
					{
						value.datphongs.Add(this);
						this._tenlp = value.tenlp;
					}
					else
					{
						this._tenlp = default(string);
					}
					this.SendPropertyChanged("loaiphong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_datphong", Storage="_nhanvien", ThisKey="manv", OtherKey="manv", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.datphongs.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.datphongs.Add(this);
						this._manv = value.manv;
					}
					else
					{
						this._manv = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.datphong = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.datphong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dichvu")]
	public partial class dichvu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madv;
		
		private string _tendv;
		
		private System.Nullable<decimal> _gia;
		
		private EntitySet<hoadon> _hoadons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadvChanging(string value);
    partial void OnmadvChanged();
    partial void OntendvChanging(string value);
    partial void OntendvChanged();
    partial void OngiaChanging(System.Nullable<decimal> value);
    partial void OngiaChanged();
    #endregion
		
		public dichvu()
		{
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madv", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madv
		{
			get
			{
				return this._madv;
			}
			set
			{
				if ((this._madv != value))
				{
					this.OnmadvChanging(value);
					this.SendPropertyChanging();
					this._madv = value;
					this.SendPropertyChanged("madv");
					this.OnmadvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendv", DbType="NVarChar(20)")]
		public string tendv
		{
			get
			{
				return this._tendv;
			}
			set
			{
				if ((this._tendv != value))
				{
					this.OntendvChanging(value);
					this.SendPropertyChanging();
					this._tendv = value;
					this.SendPropertyChanged("tendv");
					this.OntendvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Money")]
		public System.Nullable<decimal> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dichvu_hoadon", Storage="_hoadons", ThisKey="madv", OtherKey="madv")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.dichvu = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.dichvu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoadon")]
	public partial class hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mahd;
		
		private string _madp;
		
		private string _madv;
		
		private System.DateTime _ngaylap;
		
		private decimal _tongtien;
		
		private EntityRef<datphong> _datphong;
		
		private EntityRef<dichvu> _dichvu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahdChanging(string value);
    partial void OnmahdChanged();
    partial void OnmadpChanging(string value);
    partial void OnmadpChanged();
    partial void OnmadvChanging(string value);
    partial void OnmadvChanged();
    partial void OnngaylapChanging(System.DateTime value);
    partial void OnngaylapChanged();
    partial void OntongtienChanging(decimal value);
    partial void OntongtienChanged();
    #endregion
		
		public hoadon()
		{
			this._datphong = default(EntityRef<datphong>);
			this._dichvu = default(EntityRef<dichvu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahd", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahd
		{
			get
			{
				return this._mahd;
			}
			set
			{
				if ((this._mahd != value))
				{
					this.OnmahdChanging(value);
					this.SendPropertyChanging();
					this._mahd = value;
					this.SendPropertyChanged("mahd");
					this.OnmahdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madp", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string madp
		{
			get
			{
				return this._madp;
			}
			set
			{
				if ((this._madp != value))
				{
					if (this._datphong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadpChanging(value);
					this.SendPropertyChanging();
					this._madp = value;
					this.SendPropertyChanged("madp");
					this.OnmadpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madv", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string madv
		{
			get
			{
				return this._madv;
			}
			set
			{
				if ((this._madv != value))
				{
					if (this._dichvu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadvChanging(value);
					this.SendPropertyChanging();
					this._madv = value;
					this.SendPropertyChanged("madv");
					this.OnmadvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylap", DbType="Date NOT NULL")]
		public System.DateTime ngaylap
		{
			get
			{
				return this._ngaylap;
			}
			set
			{
				if ((this._ngaylap != value))
				{
					this.OnngaylapChanging(value);
					this.SendPropertyChanging();
					this._ngaylap = value;
					this.SendPropertyChanged("ngaylap");
					this.OnngaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Money NOT NULL")]
		public decimal tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="datphong_hoadon", Storage="_datphong", ThisKey="madp", OtherKey="madp", IsForeignKey=true)]
		public datphong datphong
		{
			get
			{
				return this._datphong.Entity;
			}
			set
			{
				datphong previousValue = this._datphong.Entity;
				if (((previousValue != value) 
							|| (this._datphong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._datphong.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._datphong.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._madp = value.madp;
					}
					else
					{
						this._madp = default(string);
					}
					this.SendPropertyChanged("datphong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dichvu_hoadon", Storage="_dichvu", ThisKey="madv", OtherKey="madv", IsForeignKey=true)]
		public dichvu dichvu
		{
			get
			{
				return this._dichvu.Entity;
			}
			set
			{
				dichvu previousValue = this._dichvu.Entity;
				if (((previousValue != value) 
							|| (this._dichvu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dichvu.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._dichvu.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._madv = value.madv;
					}
					else
					{
						this._madv = default(string);
					}
					this.SendPropertyChanged("dichvu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makh;
		
		private string _hoten;
		
		private string _cmnd;
		
		private string _sdt;
		
		private string _email;
		
		private string _diachi;
		
		private EntitySet<datphong> _datphongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhChanging(string value);
    partial void OnmakhChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    #endregion
		
		public khachhang()
		{
			this._datphongs = new EntitySet<datphong>(new Action<datphong>(this.attach_datphongs), new Action<datphong>(this.detach_datphongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_datphong", Storage="_datphongs", ThisKey="makh", OtherKey="makh")]
		public EntitySet<datphong> datphongs
		{
			get
			{
				return this._datphongs;
			}
			set
			{
				this._datphongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_datphongs(datphong entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_datphongs(datphong entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaiphong")]
	public partial class loaiphong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tenlp;
		
		private int _soluongtrong;
		
		private int _giaphong;
		
		private int _soluongco;
		
		private EntitySet<datphong> _datphongs;
		
		private EntitySet<phong> _phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntenlpChanging(string value);
    partial void OntenlpChanged();
    partial void OnsoluongtrongChanging(int value);
    partial void OnsoluongtrongChanged();
    partial void OngiaphongChanging(int value);
    partial void OngiaphongChanged();
    partial void OnsoluongcoChanging(int value);
    partial void OnsoluongcoChanged();
    #endregion
		
		public loaiphong()
		{
			this._datphongs = new EntitySet<datphong>(new Action<datphong>(this.attach_datphongs), new Action<datphong>(this.detach_datphongs));
			this._phongs = new EntitySet<phong>(new Action<phong>(this.attach_phongs), new Action<phong>(this.detach_phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenlp", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tenlp
		{
			get
			{
				return this._tenlp;
			}
			set
			{
				if ((this._tenlp != value))
				{
					this.OntenlpChanging(value);
					this.SendPropertyChanging();
					this._tenlp = value;
					this.SendPropertyChanged("tenlp");
					this.OntenlpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluongtrong", DbType="Int NOT NULL")]
		public int soluongtrong
		{
			get
			{
				return this._soluongtrong;
			}
			set
			{
				if ((this._soluongtrong != value))
				{
					this.OnsoluongtrongChanging(value);
					this.SendPropertyChanging();
					this._soluongtrong = value;
					this.SendPropertyChanged("soluongtrong");
					this.OnsoluongtrongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaphong", DbType="Int NOT NULL")]
		public int giaphong
		{
			get
			{
				return this._giaphong;
			}
			set
			{
				if ((this._giaphong != value))
				{
					this.OngiaphongChanging(value);
					this.SendPropertyChanging();
					this._giaphong = value;
					this.SendPropertyChanged("giaphong");
					this.OngiaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluongco", DbType="Int NOT NULL")]
		public int soluongco
		{
			get
			{
				return this._soluongco;
			}
			set
			{
				if ((this._soluongco != value))
				{
					this.OnsoluongcoChanging(value);
					this.SendPropertyChanging();
					this._soluongco = value;
					this.SendPropertyChanged("soluongco");
					this.OnsoluongcoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_datphong", Storage="_datphongs", ThisKey="tenlp", OtherKey="tenlp")]
		public EntitySet<datphong> datphongs
		{
			get
			{
				return this._datphongs;
			}
			set
			{
				this._datphongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_phong", Storage="_phongs", ThisKey="tenlp", OtherKey="tenlp")]
		public EntitySet<phong> phongs
		{
			get
			{
				return this._phongs;
			}
			set
			{
				this._phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_datphongs(datphong entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = this;
		}
		
		private void detach_datphongs(datphong entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = null;
		}
		
		private void attach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = this;
		}
		
		private void detach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manv;
		
		private string _macv;
		
		private string _hoten;
		
		private System.DateTime _ngaysinh;
		
		private string _gioitinh;
		
		private string _sdt;
		
		private string _cmnd;
		
		private string _diachi;
		
		private string _email;
		
		private EntitySet<datphong> _datphongs;
		
		private EntityRef<chucvu> _chucvu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OnmacvChanging(string value);
    partial void OnmacvChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnngaysinhChanging(System.DateTime value);
    partial void OnngaysinhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public nhanvien()
		{
			this._datphongs = new EntitySet<datphong>(new Action<datphong>(this.attach_datphongs), new Action<datphong>(this.detach_datphongs));
			this._chucvu = default(EntityRef<chucvu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macv", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string macv
		{
			get
			{
				return this._macv;
			}
			set
			{
				if ((this._macv != value))
				{
					if (this._chucvu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmacvChanging(value);
					this.SendPropertyChanging();
					this._macv = value;
					this.SendPropertyChanged("macv");
					this.OnmacvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="Char(9) NOT NULL", CanBeNull=false)]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(30)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_datphong", Storage="_datphongs", ThisKey="manv", OtherKey="manv")]
		public EntitySet<datphong> datphongs
		{
			get
			{
				return this._datphongs;
			}
			set
			{
				this._datphongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chucvu_nhanvien", Storage="_chucvu", ThisKey="macv", OtherKey="macv", IsForeignKey=true)]
		public chucvu chucvu
		{
			get
			{
				return this._chucvu.Entity;
			}
			set
			{
				chucvu previousValue = this._chucvu.Entity;
				if (((previousValue != value) 
							|| (this._chucvu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chucvu.Entity = null;
						previousValue.nhanviens.Remove(this);
					}
					this._chucvu.Entity = value;
					if ((value != null))
					{
						value.nhanviens.Add(this);
						this._macv = value.macv;
					}
					else
					{
						this._macv = default(string);
					}
					this.SendPropertyChanged("chucvu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_datphongs(datphong entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_datphongs(datphong entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phong")]
	public partial class phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maphong;
		
		private string _tenlp;
		
		private System.Nullable<bool> _tinhtrang;
		
		private EntityRef<loaiphong> _loaiphong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphongChanging(string value);
    partial void OnmaphongChanged();
    partial void OntenlpChanging(string value);
    partial void OntenlpChanged();
    partial void OntinhtrangChanging(System.Nullable<bool> value);
    partial void OntinhtrangChanged();
    #endregion
		
		public phong()
		{
			this._loaiphong = default(EntityRef<loaiphong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="Char(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this.OnmaphongChanging(value);
					this.SendPropertyChanging();
					this._maphong = value;
					this.SendPropertyChanged("maphong");
					this.OnmaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenlp", DbType="VarChar(10)")]
		public string tenlp
		{
			get
			{
				return this._tenlp;
			}
			set
			{
				if ((this._tenlp != value))
				{
					if (this._loaiphong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntenlpChanging(value);
					this.SendPropertyChanging();
					this._tenlp = value;
					this.SendPropertyChanged("tenlp");
					this.OntenlpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="Bit")]
		public System.Nullable<bool> tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this.OntinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrang = value;
					this.SendPropertyChanged("tinhtrang");
					this.OntinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_phong", Storage="_loaiphong", ThisKey="tenlp", OtherKey="tenlp", IsForeignKey=true)]
		public loaiphong loaiphong
		{
			get
			{
				return this._loaiphong.Entity;
			}
			set
			{
				loaiphong previousValue = this._loaiphong.Entity;
				if (((previousValue != value) 
							|| (this._loaiphong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaiphong.Entity = null;
						previousValue.phongs.Remove(this);
					}
					this._loaiphong.Entity = value;
					if ((value != null))
					{
						value.phongs.Add(this);
						this._tenlp = value.tenlp;
					}
					else
					{
						this._tenlp = default(string);
					}
					this.SendPropertyChanged("loaiphong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _tentaikhoan;
		
		private string _hoten;
		
		private string _matkhau;
		
		private string _quyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntentaikhoanChanging(string value);
    partial void OntentaikhoanChanged();
    partial void OnhotenChanging(string value);
    partial void OnhotenChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnquyenChanging(string value);
    partial void OnquyenChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentaikhoan", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string tentaikhoan
		{
			get
			{
				return this._tentaikhoan;
			}
			set
			{
				if ((this._tentaikhoan != value))
				{
					this.OntentaikhoanChanging(value);
					this.SendPropertyChanging();
					this._tentaikhoan = value;
					this.SendPropertyChanged("tentaikhoan");
					this.OntentaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoten", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string hoten
		{
			get
			{
				return this._hoten;
			}
			set
			{
				if ((this._hoten != value))
				{
					this.OnhotenChanging(value);
					this.SendPropertyChanging();
					this._hoten = value;
					this.SendPropertyChanged("hoten");
					this.OnhotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyen", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string quyen
		{
			get
			{
				return this._quyen;
			}
			set
			{
				if ((this._quyen != value))
				{
					this.OnquyenChanging(value);
					this.SendPropertyChanging();
					this._quyen = value;
					this.SendPropertyChanged("quyen");
					this.OnquyenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
